# Generated by Django 3.2.10 on 2021-12-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position1', models.FloatField()),
                ('position2', models.FloatField()),
                ('position3', models.FloatField()),
                ('position4', models.FloatField()),
                ('position5', models.FloatField()),
                ('position6', models.FloatField()),
                ('position7', models.FloatField()),
                ('position8', models.FloatField()),
                ('position9', models.FloatField()),
                ('position10', models.FloatField()),
                ('position11', models.FloatField()),
                ('position12', models.FloatField()),
                ('position13', models.FloatField()),
                ('position14', models.FloatField()),
                ('position15', models.FloatField()),
                ('position16', models.FloatField()),
                ('position17', models.FloatField()),
                ('position18', models.FloatField()),
                ('position19', models.FloatField()),
                ('position20', models.FloatField()),
                ('position21', models.FloatField()),
                ('position22', models.FloatField()),
                ('position23', models.FloatField()),
                ('position24', models.FloatField()),
                ('position25', models.FloatField()),
                ('position26', models.FloatField()),
                ('position27', models.FloatField()),
                ('position28', models.FloatField()),
                ('position29', models.FloatField()),
                ('position30', models.FloatField()),
                ('xlabel', models.FloatField()),
                ('ylabel', models.FloatField()),
            ],
        ),
    ]
