# Generated by Django 3.2.10 on 2021-12-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
            ],
        ),
    ]
